version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: fullstack-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: fullstack_db
      MYSQL_USER: fullstack_user
      MYSQL_PASSWORD: fullstack_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - fullstack-network

  # Optional: phpMyAdmin for database management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: fullstack-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_USER: fullstack_user
      PMA_PASSWORD: fullstack_password
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - fullstack-network

volumes:
  mysql_data:
    driver: local

networks:
  fullstack-network:
    driver: bridge